### ISSUE TITLE
Cannot install sandstorm in Fedora 23, /0.response-json’: No such file or directory

### ISSUE THREAD

**Issue by nhducit** [sandstorm-io/sandstorm#1315]
error

```
Congratulations! We have registered your <domain>.sandcats.io name.
Your credentials to use it are in /opt/sandstorm/var/sandcats; consider making a backup.
Now we're going to auto-configure HTTPS for your server.

* This will take about 30 seconds, and needs no input from you.
* Thanks to GlobalSign for their help making this happen.

Generating certificate request...
Requesting certificate (BE PATIENT)...
chmod: cannot access ‘var/sandcats/https/<domain>.sandcats.io/0.response-json’: No such file or directory
```

**Comment by paulproteus** [comment]
Hi @nhducit ,

I think there was a problem on our end reaching the GlobalSign API. I suppose we should make the installer resilient to this. I'll leave this open until we do.

Having said that, if you do a fresh install, it should work OK.

**Comment by paulproteus** [comment]
Also it should work OK if you start the Sandstorm service anyway; it'll self-heal the problem away.

**Comment by paulproteus** [comment]
I _think_ anyway.

**Comment by paulproteus** [comment]
Will dig more into this tomorrow. Self-assigning so I don't lose it!

**Comment by nhducit** [comment]
In my company PC (fedora 23):
I reinstall sandstorm and bypass enter domain.

It is installed succesfully, but when use command "sandstorm start", terminal said that I don't have permission. So I use "sudo sandstorm start", terminal said that "command not found".

Everything work fine with my PC at home (Ubuntu 14.04)

**Comment by paulproteus** [comment]
Sounds like there are two issues here.

- If the GlobalSign API (via sandcats.io) breaks, don't crash the installer.

- Fedora 23 might not have `/usr/local/bin` on `$PATH` which means `sudo sandstorm start` is bad advice. 

I'll keep this assigned to me to see if I can examine it when examining other installer issues in the next 0-2 weeks.

**Comment by paulproteus** [comment]
De-assigning from me because I haven't resolved in the past two weeks and I don't think I'll be able to in the next two.

**Comment by rdd2** [comment]
I just ran into the same thing on Ubuntu 14.04 bare metal server. Is there any way to work around this?

**Comment by paulproteus** [comment]
Thanks for the new information, @rdd2 ! I'll look into the sandcats service to see what I can find as the reason for this, and work on making the installer more robust.

**Comment by DailanM** [comment]
Having the same issue on a fedora 24 server.

**Comment by Geoegroeg** [comment]
Apparently the installer was not made more resilient and the same issue still occurs as of today when it cannot reach the SSL API. It does appear to assign the domain name and then occupy the selection but cannot complete the installation process.

Bare metal ubuntu 18.04lts
