### ISSUE TITLE
Sandstorm on VirtualBox, I sign in with Github and gets stuck on loading page

### ISSUE THREAD

**Issue by Snarkly** [sandstorm-io/sandstorm#644]
The first picture is before I signed in ![screenshot from 2015-07-30 13 22 42](https://cloud.githubusercontent.com/assets/8492776/8990096/1a5b950a-36be-11e5-97b6-971eb742e75e.png) The second picture is after I signed in using GitHub ![screenshot from 2015-07-30 13 18 44](https://cloud.githubusercontent.com/assets/8492776/8990030/c42e7314-36bd-11e5-88ed-4f08005d4a12.png) 
And this didn't seem to help https://github.com/sandstorm-io/sandstorm/pull/625?utm_content=buffer27383&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

**Comment by paulproteus** [comment]
For what it's worth, I think the problem (per Twitter conversation) is
something about your networking setup that is causing websockets to fail. I
don't have any particular insight yet into what would cause that, though.
)-:

If we start providing HTTPS to Sandstorm users (when using the sandcats.io
domain), that might help this, since there could be some middlebox doing
something weird to TCP connections.

**Comment by paulproteus** [comment]
But that is all to say -- I don't think VirtualBox in particular is the
problem here, since I know I personally run Sandstorm in VirtualBox for
development.

**Comment by dwrensha** [comment]
(Link to the Twitter conversation for context: https://twitter.com/_opXpress/status/626482888196943872)

**Comment by Snarkly** [comment]
Paulproteus, I was wondering if HTTPS would eventually be provide, you should start providing it. I do have a question about my sandstorm.conf file 
SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=http://jmulls.sandcats.io:6080
WILDCARD_HOST=*.jmulls.sandcats.io:6080
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SANDCATS_BASE_DOMAIN=sandcats.io
Should I change BIND or BASE_URL to http://127.0.0.1:6080/  The reason I'm asking is because I can try to go there and I get this error message>> Error looking up DNS TXT records for host '127.0.0.1': queryTxt ECONNREFUSED This Sandstorm server's main interface is at: http://jmulls.sandcats.io:6080 The DNS server refused the connection, which means either your DNS server is down/unreachable, or the server has misconfigured their DNS. If you are the server admin and want to use this address as the main interface, edit /opt/sandstorm/sandstorm.conf, modify the BASE_URL setting, and restart. If you got here after trying to log in via OAuth (e.g. through Github or Google), the problem is probably that the OAuth callback URL was set wrong. You need to
update it through the respective login provider's management console. 
  I'm also trying Zeronet on Windows and I have no problem going to my site address http://127.0.0.1:43110/1FjxvRMjBw5CUKpY3TCn76tszxHegohFqV but I can't get it to load on my VirtualBox and Ubuntu, so I thought maybe I needed to set sandstorm.conf  to http://127.0.0.1

**Comment by kentonv** [comment]
FWIW, websockets failures _shouldn't_ break everything, because Meteor should fall back to old-fashion "comet" mechanisms (via SockJS). So I am confused.

Regarding your question: BASE_URL must match what the user types into the browser. If you set it to http://127.0.0.1:6080, you're saying that you will always connect by typing "http://127.0.0.1:6080" into your browser. That's OK, but you'll run into problems because WILDCARD_HOST -- unfortunately, there is no such thing as a "wildcard IP address". Sandstorm requires a working wildcard host to operate; see:

https://docs.sandstorm.io/en/latest/administering/wildcard/

If you want to run a Sandstorm server accessible only locally, then you should set:

    BASE_URL=http://local.sandstorm.io:6080
    WILDCARD_HOST=*.local.sandstorm.io:6080

`local.sandstorm.io` and `*.local.sandstorm.io` resolve to 127.0.0.1.

As for BIND_IP, setting that to 127.0.0.1 will mean that Sandstorm only accepts connections on 127.0.0.1, i.e. from the local machine. You can certainly set that once you've changed the config to `local.sandstorm.io`.

Note that if you want a localhost server, the easiest way to set it up is by choosing a "dev mode" server in the install script.

**Comment by Snarkly** [comment]
Thanks kentonv, I might try to set it to local.sandstorm.io:6080 to see what it does. I'd like to find someone to get on teamviewer and help me figure it out, because it's driving me nuts trying to figure it out.

**Comment by Snarkly** [comment]
I couldn't figure out why sandstorm wasn't working for me so I uninstalled it. If you guys ever figure out what the problem is please contact me and let me know. Thank you all for your help.

**Comment by kentonv** [comment]
Hey @Snarkly, I think we found the problem: There's a bug which causes github login to fail if you haven't set a name on your github account. (For example, in my profile my name is "Kenton Varda".)

Do you see the same problem if you try to log into https://oasis.sandstorm.io ? Does it go away if you set a name on your profile?

**Comment by kentonv** [comment]
(#676 fixes that problem, though it's not released yet.)

**Comment by Snarkly** [comment]
Thanks Kenton but I uninstalled sandstorm. I will reinstall it when #676 is released

**Comment by kentonv** [comment]
@Snarkly That's why I asked you to try it on https://oasis.sandstorm.io -- you don't need to install anything.

Anyway #676 has been released now (though Oasis hasn't been updated yet).

**Comment by Snarkly** [comment]
Kenton I set my name on my github account and tried to log into https://oasis.sandstorm.io/ It seems to have logged me in, you can see my name at the top right corner, but I can't go to the apps page.
![sandstorm3](https://cloud.githubusercontent.com/assets/8492776/9369798/93d32822-4699-11e5-8c5b-5e23c85e224d.jpg)

**Comment by paulproteus** [comment]
That's the expected behavior. It means you've successfully logged in

But there's also clearly a UX issue.

@neynah do you have a suggestion for what we should display on the front
page, if you're logged in as an account that isn't permitted to create app
instances? (AKA the user is a "guest")

If you'd submit an issue with a suggestion, I'd be so grateful, so we can
avoid confusing people.

**Comment by neynah** [comment]
To me, the strangest thing is enabling login for guests who can't access Sandstorm anyway. Unless there is a specific reason for this it probably shouldn't be an option. (I may be missing something here).

Since the beta is closed, guests can't install apps but they should still be able to view the app list (without having install options). E.g. Have a link on the top bar that says "Apps." But this change seems redundant as we'll be have open beta soon.

For now, I would do something like this (but less ugly):

![guest-login1](https://cloud.githubusercontent.com/assets/855341/9370852/6aeb8ba4-4688-11e5-9a1d-51abae73264c.png)

**Comment by paulproteus** [comment]
The things they can do are:

* View grains that other people share with them, with the name that they
log in as flowing into the app (e.g. showing their name on an Etherpad)

* Share grains that they have received access to

The things they can't do are:

* Create new grains

* See a "Shared with me" tab <-- honestly I think this is a bug, and we
should show a "Shared with me" tab for "guests"


David can confirm/deny if the above is accurate, and Kenton can too but I
mentioned David first with the goal of minimizing Kenton as a bottleneck.

Getting this messaging right is pretty important IMHO for making sure that
"Sandstorm sharing" is as viral as it can be.

**Comment by dwrensha** [comment]
> See a "Shared with me" tab <-- honestly I think this is a bug, and we should show a "Shared with me" tab for "guests"

Guests do get a "Shared With Me" tab. If you've found a situation where that doesn't happen, please file a bug!

Otherwise, confirmed.

**Comment by neynah** [comment]
Ahh I see. Yes, then it seems a "Shared with me" tab should exist. Although to the guest it would be equivalent to "Grains." Which would have a list of grains they have access to, they just wouldn't be able to create any. Looks like I have more things to design and copy to write. :d

**Comment by Snarkly** [comment]
I've had the worst luck trying to get sandstorm to run.

**Comment by paulproteus** [comment]
When I am at https://oasis.sandstorm.io/ and I have logged in as a guest user, I have zero clue where to click to see my "Shared with me" tab. I see the screenshot that @snarkly saw, where there is nothing I can click on to see "Shared with me". Presumably I should be redirected to my "Files list"?

**Comment by dwrensha** [comment]
> When I am at https://oasis.sandstorm.io/ and I have logged in as a guest user, I have zero clue where to click to see my "Shared with me" tab.

Ah. That's probably because you have had nothing shared with you. We currently don't display a "Shared With Me" tab in that case.

**Comment by kentonv** [comment]
Note that, for Oasis, the concept of "guest" will go away soon, as we'll have a (very limited) free tier.

But for private Sandstorm servers it will still be a thing.

**Comment by kentonv** [comment]
In any case I think we've confirmed that @Snarkly's problem was the bug with unnamed github accounts. This is fixed in the most recent release build and will fixed on Oasis "soon".

**Comment by Snarkly** [comment]
Kenton I was able to log in but can't go to the apps page. If I reinstall sandstorm on my virtual box with ubuntu will I be able to go to the apps page then?

**Comment by kentonv** [comment]
@Snarkly Right. The reason you can't on Oasis is because you haven't been invited to Oasis.

**Comment by Snarkly** [comment]
Ok thanks Kenton. I'll let you know what happens when I install it on Ubuntu.

**Comment by Snarkly** [comment]
Check this out, I'm still having problems but this time it's with my port. I installed sandstorm and when I tried to click on the link to go to admin page it says unable to connect. I opened that port a few weeks back but now having problems with it. I've allowed it through my fire wall. I also contacted my internet service provider and he said looked open on their end. They're going to send out a technician in a few day to see if I'm having problems with my DSL box. I've tired port checkers and they said it was closed, when it shouldn't be. So the bottom line is my port seems to be open but for some reason I can't use it now. I really have bad luck.

**Comment by Snarkly** [comment]
I have a question about ports. I have port 6080 open and I also allowed it through my firewall, but I can't access that port. It was working a few weeks back. I used canyouseeme to check the port but it says the port is closed. I had my internet service provider to check the port and even they said the port is open. So apparently the port is open but something is stopping me from using it. Do any of you know of anything that might cause a problem like this. I even tried DMZ and still couldn't  access the port.

**Comment by paulproteus** [comment]
Hi @Snarkly ,

Sorry that this was left unresolved for a long time. Did you manage to resolve your issues?

If you gave up on Sandstorm, then I'm sorry about that!

Either way, I would love to know what happened.

Thanks,

Asheesh.

**Comment by Snarkly** [comment]
Hi Paul I did get SandStorm up and running but I do have  a question, how do you delete a grain or rename a grain.

**Comment by paulproteus** [comment]
Glad to hear you got Sandstorm working.

You can delete a grain and rename it by clicking around in the "top bar" -
see https://docs.sandstorm.io/en/latest/using/top-bar/ for details!

**Comment by zarvox** [comment]
Since it looks like everything got sorted out here, I'm going to go ahead and close this issue.

Feel free to open a new issue if anything else comes up!

**Comment by Snarkly** [comment]
Go ahead and close it.
